### ISSUE TITLE
Apply pix2pix model

### ISSUE THREAD

**Issue by akamob** [nudro/video-cyclegan#1]
Hi, Thank you for the great work.

I use [this](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) repository to train a pix2pix model, I want to use my checkpoints to test your work.

After replacing your **latest_net_G.pth** with mine and run command: **python main.py --name summer2winter_yosemite_pretrained --model test --preprocess none --no_dropout**, I got this error:
```
----------------- Options ---------------
         	aspect_ratio: 1.0                      	 
           	batch_size: 1                        	 
      	checkpoints_dir: ./checkpoints            	 
            	crop_size: 256                      	 
             	dataroot: None                     	 
         	dataset_mode: single                   	 
            	direction: AtoB                     	 
      	display_winsize: 256                      	 
                	epoch: latest                   	 
                 	eval: False                    	 
              	gpu_ids: 0                        	 
            	init_gain: 0.02                     	 
            	init_type: normal                   	 
             	input_nc: 3                        	 
              	isTrain: False                    		 [default: None]
            	load_iter: 0                        		 [default: 0]
            	load_size: 256                      	 
     	max_dataset_size: inf                      	 
                	model: test                     	 
         	model_suffix:                          	 
           	n_layers_D: 3                        	 
                 	name: summer2winter_yosemite_pretrained    [default: experiment_name]
                  	ndf: 64                       	 
                 	netD: basic                    	 
                 	netG: resnet_9blocks           	 
                  	ngf: 64                       	 
           	no_dropout: True                     		 [default: False]
              	no_flip: False                    	 
                 	norm: instance                 	 
             	num_test: 50                       	 
          	num_threads: 4                        	 
            	output_nc: 3                        	 
                	phase: test                     	 
           	preprocess: none                     		 [default: resize_and_crop]
          	results_dir: ./results/               	 
       	serial_batches: False                    	 
               	suffix:                          	 
              	verbose: False                    	 
----------------- End -------------------
initialize network with normal
model [TestModel] was created
loading the model from ./checkpoints/summer2winter_yosemite_pretrained/latest_net_G.pth
Traceback (most recent call last):
  File "main.py", line 23, in <module>
	model.setup(opt)           	# regular setup: load and print networks; create schedulers
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/base_model.py", line 88, in setup
	self.load_networks(load_suffix)
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/base_model.py", line 198, in load_networks
	self.__patch_instance_norm_state_dict(state_dict, net, key.split('.'))
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/base_model.py", line 174, in __patch_instance_norm_state_dict
	self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/base_model.py", line 174, in __patch_instance_norm_state_dict
	self.__patch_instance_norm_state_dict(state_dict, getattr(module, key), keys, i + 1)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
	raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Sequential' object has no attribute 'model'
```
I try to change `netG: resnet_9blocks` to `netG: unet_256` in **test_opt.txt**, but I still got same error.

May i have your suggestions to use pix2pix model?
Any help is much appreciated:)

**Comment by akamob** [comment]
Hi, @nudro,

I use CycleGAN model to test the grayscale images, I run the following command:
`python main.py --name summer2winter_yosemite_pretrained --model test --batch_size 1 --preprocess resize_and_crop --load_size 256 --crop_size 256 --input_nc 1 --output_nc 1 --no_dropout`
And I got this error:
```
Opening the video...
size: (256, 256)
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
currentFrame: 1
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    model.test()
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/base_model.py", line 105, in test
    self.forward()
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/test_model.py", line 65, in forward
    self.fake = self.netG(self.real)  # G(real)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/networks.py", line 373, in forward
    return self.model(input)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 1, 7, 7], expected input[1, 3, 262, 262] to have 1 channels, but got 3 channels instead
```

May i have your suggestions to fix this problem?
Any help is much appreciated!

**Comment by nudro** [comment]
In the `main.py`, those aren't the arguments passed in the script. I believe you're referring to the official CycleGAN implementation at https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix. If you just want to use a pretrained model like summer2winter, I'd explore their Colab notebooks and tailor your use case to their code.

**Comment by akamob** [comment]
Hi, @nudro, Thank you for your reply.

Yes, I trained my CycleGAN model on the official repository and replaced your checkpoints with my model.
I let CycleGAN convert the grayscale image into RGB image.

For testing, I hope use video as input but the official CycleGAN seems to test the model with single image.
So I want to test my model based on your work.

**Comment by nudro** [comment]
Ok I see. Based on your error it looks like during `model.test` you're passing a 3-channel frame/image, and it wants a 1-channel.

**Comment by akamob** [comment]
Hi, Thank you for your reply.

I use [python pillow](https://pillow.readthedocs.io/en/stable/handbook/concepts.html) to check my image type, it shows: Pillow:  **I (256, 256)**. I obtain my test video by using ffmpeg to convert these images to video.

Besides, I tried to run this command: `python main.py --name summer2winter_yosemite_pretrained --model test --batch_size 1 --preprocess resize_and_crop --load_size 256 --crop_size 256 --no_dropout`

And I got this error:
```
initialize network with normal
model [TestModel] was created
loading the model from ./checkpoints/summer2winter_yosemite_pretrained/latest_net_G.pth
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/base_model.py", line 88, in setup
    self.load_networks(load_suffix)
  File "/home/lk3696/cyclegan_video/video-cyclegan/models/base_model.py", line 199, in load_networks
    net.load_state_dict(state_dict)
  File "/home/lk3696/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	size mismatch for model.1.weight: copying a param with shape torch.Size([64, 1, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 3, 7, 7]).
	size mismatch for model.26.weight: copying a param with shape torch.Size([1, 64, 7, 7]) from checkpoint, the shape in current model is torch.Size([3, 64, 7, 7]).
	size mismatch for model.26.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([3]).
```

Did I miss something in the configuration?
Any help is much appreciated!

**Comment by nudro** [comment]
If you're trying to use pix2pix, I'd refer to the official repository for
guidance.
